### ISSUE TITLE
spring-cloud-bindings download returning 404 when running spring buildpack

### ISSUE THREAD

**Issue by bjongbloedt** [paketo-buildpacks/spring-boot#225]
I have been getting a 404 this morning when attempting to build my docker container using the Spring Boot Build Pack with the information below.  I had a build running last night that successfully resolved the jar, so my guess something must have happened last night to the repo.  Please let me know if more information is required to hunt this down, Thanks!

```
     [creator]     Paketo Spring Boot Buildpack 5.13.0
    [creator]       https://github.com/paketo-buildpacks/spring-boot
    [creator]       Build Configuration:
    [creator]         $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
    [creator]       Launch Configuration:
    [creator]         $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
    [creator]         $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
    [creator]       Creating slices from layers index
    [creator]         dependencies (63.9 MB)
    [creator]         spring-boot-loader (281.8 KB)
    [creator]         snapshot-dependencies (0.0 B)
    [creator]         application (217.2 KB)
    [creator]       Launch Helper: Contributing to layer
    [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
    [creator]       Spring Cloud Bindings 1.10.0: Contributing to layer
    [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
    [creator]     unable to invoke layer creator
    [creator]     unable to contribute spring-cloud-bindings layer
    [creator]     unable to get dependency spring-cloud-bindings
    [creator]     unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
    [creator]     could not download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar: 404
    [creator]     ERROR: failed to build: exit status 1
```

## Expected Behavior
Spring cloud binding should not return a 404

## Current Behavior
It appears that the buildpack cant find the bindings jar

## Steps to Reproduce

1. Run `./gradlew bootBuildImage` on a spring boot project
2. Observe failure when trying to resolve the spring-cloud-bindings jar

**Comment by pzpupu** [comment]
me too

**Comment by Schultz-Thomas** [comment]
Same problems, it seems to be 2 hours old bugs; Last successfully build was 2 hours ago

**Comment by dmikusa-pivotal** [comment]
Please standby. I'm seeing reports of a problem with Artifactory/repo.spring.io. I will update this thread when I have more info.

**Comment by pzpupu** [comment]
有什么临时解决办法吗？

**Comment by candrews** [comment]
> The other option is to use a dependency mapping.

How exactly does one do that when using `./gradlew bootBuildImage`?

**Comment by dmikusa-pivotal** [comment]
It works for me when I test it:

```
Paketo Spring Boot Buildpack 5.11.0
  https://github.com/paketo-buildpacks/spring-boot
  Build Configuration:
    $BP_SPRING_CLOUD_BINDINGS_DISABLED   true   whether to contribute Spring Boot cloud bindings support
  Launch Configuration:
    $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
    $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
  Creating slices from layers index
    dependencies
    spring-boot-loader
    snapshot-dependencies
    application
  Web Application Type: Contributing to layer
    Reactive web application detected
    Writing env.launch/BPL_JVM_THREAD_COUNT.default
  4 application slices
  Image labels:
    org.opencontainers.image.title
    org.opencontainers.image.version
    org.springframework.boot.version
```

Do you see `$BP_SPRING_CLOUD_BINDINGS_DISABLED   true` in the `Build Configuration` section from your build logs? This should represent the value that it's reading. My guess is that it's not reading as `true` in your case. If that's not it, include your build logs and I can take a look.

**Comment by dmikusa-pivotal** [comment]
Update on the problem. JFrog was doing a cert rotation and incorrectly redirected traffic to the wrong place. They are aware of the issue & we are awaiting a fix. Hopefully, it won't be long now. Thanks for everyone's patience.

**Comment by candrews** [comment]
> this `BP_SPRING_CLOUD_BINDINGS_DISABLED=true` did not work

This addition to `build.gradle` worked for me:

```groovy
tasks.named("bootBuildImage") {
	environment = ["BP_SPRING_CLOUD_BINDINGS_DISABLED" : "true"]
}
```

**Comment by dmikusa-pivotal** [comment]
Ah, yes. Thanks @candrews. I should have been more specific. It needs to be set in the build environment, not locally. My fault.

**Comment by TomBeckett** [comment]
@dmikusa-pivotal Will there be a post mortem?

_Not asking to be a bad guy. Just curious to understand the background for what occurred for our own post mortem._

**Comment by dmikusa-pivotal** [comment]
>@dmikusa-pivotal Will there be a post mortem?

I'll share whatever info I have. The service behind repo.spring.io is a managed service from JFrog, so I only know what they share with us about the incident.

**Comment by alexeytokar** [comment]
Looks like the issue has been resolved (for all who subscribed)

**Comment by spencergibb** [comment]
Also see https://github.com/spring-cloud/spring-cloud-bindings/issues/71 for getting spring-cloud-bindings to maven central rather than repo.spring.io for production usage

**Comment by dmikusa-pivotal** [comment]
Yes, it should be resolved now, just got an update from the vendor & it's working for me.

@TomBeckett This is what I can share, and all I know honestly.

The Spring Infra team put in a request to renew the certificate on our instance, which includes a redeploy. This should be a non-event, however, while doing this the vendor did something which caused traffic to repo.spring.io to go to repo.pivotal.io. This had happened before & we explicitly put notes in the service request to the vendor to try to prevent this from happening, but despite reminding the vendor it still happened.

We've had an open issue to publish Spring Cloud Bindings to Maven Central, but given what has happened today, we'll bump up the priority on that. When done, we won't need to worry about this going forward.

**Comment by kshkrao3** [comment]
The issue is back. I am getting 404 for the below link.
https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar

Any permanent solution for this?

**Comment by danielfelgar** [comment]
I got the same error.

**Comment by kshkrao3** [comment]
Well temporarily, I disabled the 2 properties mentioned by @dmikusa-pivotal. Since I'm using maven, here's what I did.

`<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <env>
                            <BP_SPRING_CLOUD_BINDINGS_DISABLED>true</BP_SPRING_CLOUD_BINDINGS_DISABLED>
                            <BPL_SPRING_CLOUD_BINDINGS_DISABLED>true</BPL_SPRING_CLOUD_BINDINGS_DISABLED>
                        </env>
                        <name>${project.artifactId}:${project.version}</name>
                    </image>
                    <pullPolicy>IF_NOT_PRESENT</pullPolicy>
                </configuration>
            </plugin>
        </plugins>
    </build>`

[Source](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.examples.builder-configuration)

**Comment by vladromila** [comment]
@kshkrao3's solution works for spring-boot 2.7.1 and maven builds.

**Comment by danielfelgar** [comment]
Now working fine..

**Comment by juea01** [comment]
Hi, I am trying to disable spring cloud binding package as mentioned in above comments but still during build process, it is attempting to fetch the spring-cloud-bindings-1.8.1.jar file. My Spring boot version is 2.7.1 and  Spring boot maven plugin 2.7.1. Any help would be really appreciated.
<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<env>
							<BP_SPRING_CLOUD_BINDINGS_DISABLED>true</BP_SPRING_CLOUD_BINDINGS_DISABLED>
							<BPL_SPRING_CLOUD_BINDINGS_DISABLED>true</BPL_SPRING_CLOUD_BINDINGS_DISABLED>
						</env>
						<name>ajdev/${project.artifactId}:${project.version}</name>
					</image>
					<pullPolicy>IF_NOT_PRESENT</pullPolicy>
				</configuration>
			</plugin>
		</plugins>
	</build>

**Comment by yeonnex** [comment]
still error...

**Comment by yeonnex** [comment]
still error...
